// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnrcJBu918P2GcpEqaxI7NK0nz7WszAJI',
    appId: '1:543917276390:web:db9356617edb9e59aa0f27',
    messagingSenderId: '543917276390',
    projectId: 'civic-bridge-83dbd',
    authDomain: 'civic-bridge-83dbd.firebaseapp.com',
    storageBucket: 'civic-bridge-83dbd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBidEGmU4mn3zZXScf6MGtvOIQZSBy63TM',
    appId: '1:543917276390:android:ebbb538734853d81aa0f27',
    messagingSenderId: '543917276390',
    projectId: 'civic-bridge-83dbd',
    storageBucket: 'civic-bridge-83dbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKV0KW1-rsru8v4cj1s_L6ua9hsXpLpu8',
    appId: '1:543917276390:ios:d6376affe1d50d40aa0f27',
    messagingSenderId: '543917276390',
    projectId: 'civic-bridge-83dbd',
    storageBucket: 'civic-bridge-83dbd.firebasestorage.app',
    iosBundleId: 'com.example.civicBridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKV0KW1-rsru8v4cj1s_L6ua9hsXpLpu8',
    appId: '1:543917276390:ios:d6376affe1d50d40aa0f27',
    messagingSenderId: '543917276390',
    projectId: 'civic-bridge-83dbd',
    storageBucket: 'civic-bridge-83dbd.firebasestorage.app',
    iosBundleId: 'com.example.civicBridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnrcJBu918P2GcpEqaxI7NK0nz7WszAJI',
    appId: '1:543917276390:web:ddba0f941b9fc41aaa0f27',
    messagingSenderId: '543917276390',
    projectId: 'civic-bridge-83dbd',
    authDomain: 'civic-bridge-83dbd.firebaseapp.com',
    storageBucket: 'civic-bridge-83dbd.firebasestorage.app',
  );
}
